openapi: 3.0.0
info:
  title: Code Review Chatbot
  version: 1.0.0
  description: Code Review Chatbot API

paths:

  # Email Verification Routes
  /email/verify:
    get:
      tags:
        - Verification
      summary: Verify Email View
      description: Returns the email verification view.
      responses:
        200:
          description: Email verification view returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - auth: []

  /email/verify/{id}/{hash}':
    get:
      tags:
        - Verification
      summary: Verify Email
      description: Verifies the user email.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        302:
          description: Redirect to dashboard.
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - auth: []

  /email/verification-notification:
    post:
      tags:
        - Verification
      summary: Send Verification Notification
      description: Sends a new email verification notification.
      responses:
        200:
          description: Verification link sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - auth: []


  # Authentication and User Management Routes
  /log:
    post:
      tags:
        - Log Data    
      summary: Log Data
      description: Endpoint to log data.
      responses:
        200:
          description: Data logged successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /login:
    post:
      tags:
        - User Data  
      summary: User Login
      description: Endpoint for user login.
      responses:
        200:
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /register:
    post:
      tags:
        - User Data  
      summary: User Registration
      description: Endpoint for user registration.
      responses:
        200:
          description: Registration successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /details:
    post:
      tags:
        - User Data  
      summary: User Details
      description: Returns user details.
      responses:
        200:
          description: User details returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiAuth: []

  /user:
    get:
      tags:
        - User Data  
      summary: Get User
      description: Returns the authenticated user's details.
      responses:
        200:
          description: User details returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - sanctumAuth: []

  /userinfo:
    get:
      tags:
        - User Data  
      summary: Get User Info
      description: Returns information of the authenticated user.
      responses:
        200:
          description: User info returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - sanctumAuth: []

components:
  securitySchemes:
    auth:
      type: apiKey
      in: header
      name: Authorization
    apiAuth:
      type: apiKey
      in: header
      name: API-Key
    sanctumAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Success"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Unauthorized"
    UserDetailsResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    UserInfoResponse:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string

security:
  - auth: []
