org: trau3
app: laravel
service: laravel

constructs:
    website:
        type: server-side-website
        assets:
            'public/build/assets/*': public/build/assets
            #'/css/*': public/css
            'public/favicon.ico': public/favicon.ico
            'public/robots.txt': public/robots.txt

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        OPENAI_API_KEY: ${param:OpenAIKey}
        OPENAI_REQUEST_TIMEOUT: 300
        DB_CONNECTION: mysql
        DATABASE_URL: ${param:DatabaseURL}
        SCRIPT_FILENAME: 'laravel/public/index.php'
        APP_KEY: ${param:AppKey}
        SCRIPT_NAME: '/index.php'
        FILESYSTEM_DRIVER: s3
        ASSET_URL: public/
        SESSION_DRIVER: cookie
        LOG_CHANNEL: stderr
        WEBSITE_URL: ${construct:website.url}
        AWS_BUCKET: !Ref Storage
    iam:
        role:
            statements:
                # Allow Lambda to read and write files in the S3 buckets
                - Effect: Allow
                  Action: s3:*
                  Resource:
                    - !Sub '${Storage.Arn}' # the storage bucket
                    - !Sub '${Storage.Arn}/*' # and everything inside


	
custom:
  scripts:
    hooks:
      'before:package:initialize': |
        composer install --no-dev
        php artisan event:cache
        npm ci
        npm run build
        php artisan config:clear
  lift:
    assets:
      path: public
      url: /




package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'


functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-81-fpm
        timeout: 300 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'
        vpc:
            securityGroupIds: 
                - sg-00578ac72dd8faf72
            subnetIds:
                - subnet-0612248cfdc1bd2d2
                - subnet-066e1cdcd6660204f
                - subnet-0ad891646e7f81a94
                - subnet-0c243b4b01ab53636
                - subnet-0299f07c1e8bcca96
                - subnet-01cc4ced57586bc39

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-81-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref
  - serverless-plugin-scripts
  - serverless-lift
  - serverless-offline


resources:
  Resources:
    # Create our S3 storage bucket using CloudFormation
    Storage:
      Type: AWS::S3::Bucket
