name: Deploy Server to AWS

on:
  push:
    branches: [ main ]
    paths:
      -  'server/code-review-chatbot/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
        working-directory: ./server/code-review-chatbot
      - name: Install Project Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ./server/code-review-chatbot
      - name: Deploy Environment
        run: |
          vapor team:switch --id 62804
          vapor deploy prod
        working-directory: ./server/code-review-chatbot
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
