name: Deploy

on:
  push:
    branches: [ trau3-patch-1 ]
    paths:
      -  'server/code-review-chatbot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
        working-directory: ./server/code-review-chatbot
      - name: Install Project Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ./server/code-review-chatbot
      - name: Deploy Environment
        run: vapor deploy production
        working-directory: ./server/code-review-chatbot
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
